# Generated by Django 4.2.11 on 2024-03-23 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_data_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="data",
            name="order",
        ),
    ]
